# Generated by Django 4.0 on 2021-12-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='instagram')),
                ('image_name', models.CharField(max_length=30)),
                ('image_caption', models.CharField(max_length=1000)),
            ],
        ),
    ]
