# Generated by Django 4.0 on 2021-12-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_image_comments_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
