# Generated by Django 4.0 on 2021-12-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_image_comments_remove_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
