# Generated by Django 4.0 on 2021-12-15 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_delete_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
