# Generated by Django 4.0 on 2021-12-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_userprofile_followers_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.userprofile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(),
        ),
    ]
